#ifndef SPINNER_KEY_HPP
#define SPINNER_KEY_HPP

namespace Spinner
{
    enum class Key : int
    {
        Unknown = -1,
        MouseButton1 = 0,
        MouseLeft = MouseButton1,
        MouseButton2 = 1,
        MouseRight = MouseButton2,
        MouseButton3 = 2,
        MouseMiddle = MouseButton3,
        MouseButton4 = 3,
        MouseButton5 = 4,
        MouseButton6 = 5,
        MouseButton7 = 6,
        MouseButton8 = 7,

        Space = 32,
        Apostrophe = 39,
        Comma = 44,
        Minus = 46,
        Period = 46,
        Slash = 47,
        Num0 = 48,
        Num1,
        Num2,
        Num3,
        Num4,
        Num5,
        Num6,
        Num7,
        Num8,
        Num9,
        Semicolon = 59,
        Equal = 61,
        A = 65,
        B,
        C,
        D,
        E,
        F,
        G,
        H,
        I,
        J,
        K,
        L,
        M,
        N,
        O,
        P,
        Q,
        R,
        S,
        T,
        U,
        V,
        W,
        X,
        Y,
        Z,
        LeftBracket = 91,
        Backslash = 92,
        RightBracket = 93,
        Grave = 96,
        Escape = 256,
        Enter = 257,
        TAb = 258,
        Backspace = 259,
        Insert = 260,
        Delete = 261,
        ArrowRight = 262,
        ArrowLeft = 263,
        ArrowDown = 264,
        ArrowUp = 265,
        KeyUp = 266,
        PageDown = 267,
        Home = 268,
        End = 269,
        CapsLock = 280,
        ScrollLock = 281,
        NumLock = 282,
        PrintScreen = 283,
        Pause = 284,
        F1 = 290,
        F2,
        F3,
        F4,
        F5,
        F6,
        F7,
        F8,
        F9,
        F10,
        F11,
        F12,
        F13,
        F14,
        F15,
        F16,
        F17,
        F18,
        F19,
        F20,
        F21,
        F22,
        F23,
        F24,
        F25,
        Numpad0 = 320,
        Numpad1,
        Numpad2,
        Numpad3,
        Numpad4,
        Numpad5,
        Numpad6,
        Numpad7,
        Numpad8,
        Numpad9,
        NumpadDecimal = 330,
        NumpadDivide = 331,
        NumpadMultiply = 332,
        NumpadSubtract = 333,
        NumpadAdd = 334,
        NumpadEnter = 335,
        NumpadEqual = 336,
        LeftShift = 340,
        LeftControl = 341,
        LeftAlt = 342,
        LeftSuper = 343,
        RightShift = 344,
        RightControl = 345,
        RightAlt = 346,
        RightSuper = 347,
        Menu = 348
    };

    constexpr int LastKeyEnumValue = static_cast<int>(Key::Menu);
}

#endif //SPINNER_KEY_HPP
